#!/usr/bin/env zsh

emulate zsh
set -eu -o pipefail
setopt extendedglob NO_multios


# ------------------------------------------------------------- #
#                           parameters                          #
# ------------------------------------------------------------- #

me=${0:t}

help=(
  ''
  "usage:"
  "    $me"' --files-with-tests f.mk g.mk ..   # [1]'
  "    $me"' f.mk <<< $(make -np f.mk)         # [2]'
  ''
  '    [1]: output names of files with tests'
  '    [2]: run the tests in the file'
  ''
  'the test will pass iff'
  '    for every parseAssert directive in the test file,'
  '    its regex matches >=1 substring in the make database on stdin'
  ''
  'syntax and example:'
  ''
  '    ----test.mk----'
  '    ## /var:?=str/'
  ''
  ''
  '        """""""""       <- parseAssert regex'
  '    """"""""""""""      <- parseAssert directive'
  ''
  'environment:'
  '    flags: see source code'
  )

[[ -v  HUMAN         ]] || HUMAN=           # use colors for terminal output
[[ -v  PARSE_NOTRACE ]] || PARSE_NOTRACE=   # suppress msgs on failing tests
[[ -v  PARSE_DBG     ]] || PARSE_DBG=

directiveRE='##\s*/\K.*(?=/)'


# ------------------------------------------------------------- #
#                           functions                           #
# ------------------------------------------------------------- #

p2g() {
  pcre2grep --utf $@
  }

p2g-matches() {  # succeed iff regex $1 matches in file $2; errors are fatal
  local re=$1 f=$2
  local p2g_stderr
  integer haveMatch

  p2g_stderr=$(p2g -q --regex=$re $f 2>&1) \
  && haveMatch=1 \
  || haveMatch=0

  (($#p2g_stderr == 0)) || die_p2g $re $p2g_stderr
  ((haveMatch))         || return 1
  return 0
  }

require-p2g() {
  command -v pcre2grep &>/dev/null || die_no-p2g
  }

files-with-tests() {
  dbg '%s(), args: %s' $0 "$@"
  local f
  foreach f ( $@ ) {
    if p2g-matches $directiveRE $f
    then print -r -- $f
    fi
    }
  }

get-assertREs() {
  local f_test=$1 toName=$2
  local newArr=( ${(f)"$(p2g -o --regex=$directiveRE $f_test||true)"} )
  typeset -ag $toName
  : "${(PA)toName::=${(@)newArr}}"
  }

run-test() {
  local f_test=$1
  dbg '%s(), f_test=%s' $0 $f_test

  () {
    local f_mkDB=$1

    local lines_mkDB=$(wc -l < $f_mkDB)
    dbg 'make db: %d lines' $lines_mkDB
    ((lines_mkDB>10)) || die_mkDB-lines $f_test $lines_mkDB

    local assertREs
    get-assertREs $f_test assertREs
    (($#assertREs)) || die_noAssertRE $f_test
    dbgv assertREs

    local re
    foreach re ( $assertREs ) {
      p2g-matches $re $f_mkDB || { failtrace $f_test $re; exit 1 }
      dbg 'regex matched: /%s/' $re
      }

    } =(cat)  # capture stdin

  }

failtrace() {
  local f_test=$1 re=$2

  ((! $#PARSE_NOTRACE)) || return 0

  # TODO declare as array, or immediately do foreach
  # consider whether to send `prnt` arguments (to be paired by prnt) instead

  prnt red     '✖ '
  prnt red_it   $f_test$'\n'
  prnt red    $'  parse test failed\n'

  prnt dark    '  regex: /'
  prnt regx    "$re"
  prnt dark   $'/\n'

  prnt dark   $'  no match in make database\n\n'
  }


# ------------------------------------------------------------- #
#                   functions: terminal output                  #
# ------------------------------------------------------------- #

prnt() {
  (($#HUMAN)) || { print -rn -- "$2"; return; }

  case $1 in
     (red   ) print -rn -- "$(tput setaf   1; )"
  ;; (red_it) print -rn -- "$(tput setaf   1; tput sitm; )"
  ;; (regx  ) print -rn -- "$(tput setaf 105; )"
  ;; (dark  ) print -rn -- "$(tput setaf   0; )"
  ;; (*     ) die 'internal error'
  ;;
  esac
  print -rn -- "$2"
  print -rn -- "$(tput sgr0)"
}

die() {
  print -n '[' && prnt red $me && print -n '] '
  prnt  red    'error: '
  prnt  dark   "$1"$'\n'
  exit 1
  } >&2

dbg_(){
  (($#PARSE_DBG)) || return 0
  prnt dark "[$me] $1"$'\n'
  } >&2

dbg (){ dbg_ "$(printf $1 ${@:2})"; }
dbgv(){ dbg_ "$(echo \`"$@"\`:; typeset -p1 -- $@|sed 's/^/    /')"$'\n' ; }

die_no-p2g    () { die "no pcre2grep; can't run parse tests"; }
die_mkDB-lines() { die "$1: only $2 lines in make database" ; }
die_noAssertRE() { die "$1: unexpected: no assert REs found"; }
die_p2g       () { die "pcre2grep failed, regex /$1/: $2"   ; }


# ------------------------------------------------------------- #
#                              main                             #
# ------------------------------------------------------------- #

case ${1-} in
   ( --help|-h          ) print "${(@F)help}"
;; ( ''                 ) print "${(@F)help}" >&2
;; ( --files-with-tests ) require-p2g && shift     && files-with-tests $@
;; ( *                  ) require-p2g && f_test=$1 && run-test ${f_test:?}
;;
esac
