#!/usr/bin/env zsh

# invoke from repo root

set -eu -o pipefail

url='https://github.com/user-attachments/assets/cf51baef-a7fd-434e-96ca-2ad54b62b3aa'
  # high-res image to generate downscaled icon from are not included in the repo but is available through an upload to the project's Github Wiki on this URL

opts=(
  -filter  Lanczos
  -quality 100
  -define  png:compression-level=9
  -strip
  )

foreach out res (
  misc/icon_256.png '-resize 256x256'
  misc/icon_128.png '-resize 128x128'
  ) {

  if [[ ${1-} == '--dry' ]]
  then print curl -sfL $url \| magick - $=opts $=res $out
  else       curl -sfL $url  | magick - $=opts $=res $out && ls -lh $out
  fi

  }
